# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QCLoggerApp', '0003_auto_20171205_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='name_text',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
