# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 12:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QCLoggerApp', '0004_auto_20171205_1827'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='date',
            new_name='datetime',
        ),
    ]
